# Generated by Django 4.2.23 on 2025-08-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mobile', models.CharField(max_length=15)),
                ('Salt', models.CharField(max_length=64)),
                ('PasswordHash', models.CharField(max_length=128)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceType', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('FeeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
