# Generated by Django 4.2.23 on 2025-08-27 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('TransactionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Currency', models.CharField(default='INR', max_length=10)),
                ('OrderId', models.CharField(max_length=100, unique=True)),
                ('PaymentId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Signature', models.CharField(blank=True, max_length=256, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('GatewayResponse', models.JSONField()),
                ('IdempotencyKey', models.CharField(max_length=100, unique=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.servicerequest')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.user')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'indexes': [models.Index(fields=['PaymentId'], name='api_payment_Payment_8503d5_idx'), models.Index(fields=['IdempotencyKey'], name='api_payment_Idempot_f1cba4_idx')],
            },
        ),
    ]
